require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/entity_infos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EntityInfo. As you add validations to EntityInfo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EntityInfo.create! valid_attributes
      get entity_infos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      entity_info = EntityInfo.create! valid_attributes
      get entity_info_url(entity_info)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_entity_info_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      entity_info = EntityInfo.create! valid_attributes
      get edit_entity_info_url(entity_info)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EntityInfo" do
        expect {
          post entity_infos_url, params: { entity_info: valid_attributes }
        }.to change(EntityInfo, :count).by(1)
      end

      it "redirects to the created entity_info" do
        post entity_infos_url, params: { entity_info: valid_attributes }
        expect(response).to redirect_to(entity_info_url(EntityInfo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EntityInfo" do
        expect {
          post entity_infos_url, params: { entity_info: invalid_attributes }
        }.to change(EntityInfo, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post entity_infos_url, params: { entity_info: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested entity_info" do
        entity_info = EntityInfo.create! valid_attributes
        patch entity_info_url(entity_info), params: { entity_info: new_attributes }
        entity_info.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the entity_info" do
        entity_info = EntityInfo.create! valid_attributes
        patch entity_info_url(entity_info), params: { entity_info: new_attributes }
        entity_info.reload
        expect(response).to redirect_to(entity_info_url(entity_info))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        entity_info = EntityInfo.create! valid_attributes
        patch entity_info_url(entity_info), params: { entity_info: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested entity_info" do
      entity_info = EntityInfo.create! valid_attributes
      expect {
        delete entity_info_url(entity_info)
      }.to change(EntityInfo, :count).by(-1)
    end

    it "redirects to the entity_infos list" do
      entity_info = EntityInfo.create! valid_attributes
      delete entity_info_url(entity_info)
      expect(response).to redirect_to(entity_infos_url)
    end
  end
end
